RPM_NAME         = bitmodels
RPM_SUMMARY      = bitmodels
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.1.2
RPM_RELEASE      = 1
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = gitolite@git.int.prg.relbit.com:bitmodels.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH   = 1019_rails4

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
