RPM_NAME        = libmemcached
RPM_SUMMARY     = Client library and command line tools for memcached server
RPM_LICENSE     = BSD
RPM_VERSION     = 1.0.18
RPM_RELEASE     = 1
RPM_SOURCE0     = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL         = https://launchpad.net/libmemcached/1.0/$(RPM_VERSION)/+download/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
