RPM_NAME        = ruby
RPM_SUMMARY     = Ruby lang
RPM_LICENSE     = Ruby
RPM_VERSION     = 2.1.2
RPM_VERSIO2     = 2.1.2
RPM_RELEASE     = 10
RPM_SOURCEN0    = $(RPM_NAME)-$(RPM_VERSIO2)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = http://cache.ruby-lang.org/pub/ruby/2.1/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
