RPM_NAME        = roundcubemail
RPM_SUMMARY     = Evia webmail application
RPM_LICENSE     = EULA
RPM_VERSION     = 1.0.1
RPM_RELEASE     = 11
RPM_SOURCE0     = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL         = http://sourceforge.net/projects/$(RPM_NAME)/files/$(RPM_NAME)/$(RPM_VERSION)/$(RPM_SOURCE0)
RPM_SOURCES     = horizontal_logo.png login_logo.png

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
