RPM_NAME         = bitmailer
RPM_SUMMARY      = bitmailer
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.2.0
RPM_RELEASE      = 1
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = gitolite@git.int.prg.relbit.com:bitmailer.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH   = 1068_rails4
RPM_SOURCES      = etc-init.d-bitmailer etc-logrotate.d-bitmailer usr-sbin-bitmailer usr-sbin-bitmailer-console

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
