RPM_NAME        = bitadmin-plugin-superfaktura
RPM_SUMMARY     = Internal Relbit plugin for superfaktura.sk
RPM_LICENSE     = EULA
RPM_VERSION     = 2.0
RPM_RELEASE     = 7
RPM_SOURCE0     = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL         = gitolite@git.int.prg.relbit.com:bitadmin-plugin-superfaktura.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH  = devel

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
