RPM_NAME        = libdwarf
RPM_SUMMARY     = Library to access the DWARF Debugging file format
RPM_LICENSE     = LGPLv2
RPM_VERSION     = 20140208
RPM_RELEASE     = 1
RPM_SOURCE0     = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL         = http://pkgs.fedoraproject.org/repo/pkgs/libdwarf/libdwarf-20140208.tar.gz/4dc74e08a82fa1d3cab6ca6b9610761e/$(RPM_SOURCE0)

RPM_SOURCES	= libdwarf-soname.patch

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
