RPM_NAME         = evia-template-bitoxy
RPM_SUMMARY      = evia-template-bitoxy
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.0.5
RPM_RELEASE      = 200
RPM_SOURCE0      = scientific-6-x86_64-evia-bitoxy.tar.gz
RPM_URL          = http://repo.bts.relbit.com/templates/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
