RPM_NAME        = libglog
RPM_SUMMARY     = A C++ application logging library
RPM_LICENSE     = BSD
RPM_VERSION     = 0.3.3
RPM_RELEASE     = 1
RPM_SOURCEN0    = glog-$(RPM_VERSION)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = https://google-glog.googlecode.com/files/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
