RPM_NAME         = bitsuper
RPM_SUMMARY      = bitsuper
RPM_LICENSE      = EULA
RPM_VERSION      = 2.0.5
RPM_RELEASE      = 200
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = gitolite@git.int.prg.relbit.com:bitsuper.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH   = 1061_ruby2.0
RPM_SOURCES      = etc-init.d-bitsuper etc-logrotate.d-bitsuper usr-sbin-bitsuper usr-sbin-bitsuper-console

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
