RPM_NAME         = bitdeploy
RPM_SUMMARY      = bitdeploy
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.1.0
RPM_RELEASE      = 1
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = gitolite@git.int.prg.relbit.com:bitdeploy.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH   = ruby2.1
RPM_SOURCES      = usr-sbin-bitdeploy

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
