RPM_NAME        = libicu
RPM_SUMMARY     = International Components for Unicode
RPM_LICENSE     = MIT and UCD and Public Domain
RPM_VERSION     = 52.1
RPM_VERSIO2     = 52_1
RPM_RELEASE     = 2
RPM_SOURCEN0    = icu
RPM_SOURCE0     = $(RPM_SOURCEN0)4c-$(RPM_VERSIO2)-src.tgz
RPM_URL         = http://download.icu-project.org/files/icu4c/$(RPM_VERSION)/$(RPM_SOURCE0)

RPM_SOURCES	= icu-config

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
