RPM_NAME         = evia-template-gal
RPM_SUMMARY      = evia-template-gal
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.0.5
RPM_RELEASE      = 200
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = http://repo.bts.relbit.com/templates/scientific-6-x86_64-evia-gal.tar.gz

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
