RPM_NAME         = bitaccount
RPM_SUMMARY      = bitaccount
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.2.0
RPM_RELEASE      = 1
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = gitolite@git.int.prg.relbit.com:bitaccount.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH   = 1120_ruby2.1
RPM_SOURCES      = etc-init.d-bitaccount etc-logrotate.d-bitaccount usr-sbin-bitaccount usr-sbin-bitaccount-console

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
