RPM_NAME        = sqlite
RPM_SUMMARY     = Library that implements an embeddable SQL database engine
RPM_LICENSE     = Public Domain
RPM_VERSION     = 3.8.5
RPM_VERSIO2	= 3080500
RPM_RELEASE     = 1
RPM_SOURCE0     = $(RPM_NAME)-src-$(RPM_VERSIO2).zip
RPM_URL         = http://www.sqlite.org/2014/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
