RPM_NAME         = evia-template-mail
RPM_SUMMARY      = evia-template-mail
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.1.0
RPM_RELEASE      = 1
RPM_SOURCE0      = scientific-6-x86_64-evia-mail.tar.gz
RPM_URL          = http://repo.bts.relbit.com/templates/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
