RPM_NAME        = phpMyAdmin
RPM_SUMMARY     = phpmyadmin
RPM_LICENSE     = GPL, version 2
RPM_VERSION     = 4.2.9
RPM_RELEASE     = 1
RPM_SOURCE0     = $(RPM_NAME)-$(RPM_VERSION)-english.tar.gz
RPM_URL         = http://sourceforge.net/projects/$(RPM_SUMMARY)/files/$(RPM_NAME)/$(RPM_VERSION)/$(RPM_SOURCE0)
RPM_SOURCES    	= evia-config.inc.php

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
