RPM_NAME        = haproxy
RPM_SUMMARY     = HA-Proxy is a TCP\/HTTP reverse proxy for high availability environments
RPM_LICENSE     = GPL
RPM_VERSION     = 1.5.dev22
RPM_VERSIO2     = 1.5-dev22
RPM_RELEASE     = 1
RPM_SOURCEN0    = $(RPM_NAME)-$(RPM_VERSIO2)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = http://haproxy.1wt.eu/download/1.5/src/devel/$(RPM_SOURCE0)

# Makefile internals from here on:

ROOTDIR = $(shell pwd)/../
include $(ROOTDIR)Makefile.includes

all: build_default

