#!/bin/bash
#
# Init file for hhvm
#
# Written by Dag Wie√´rs 
#
# chkconfig: - 80 12
# description: HHVM
#
# processname: hhvm
# config: /etc/sysconfig/hhvm
# config: /etc/hhvm.conf
 
source /etc/rc.d/init.d/functions
 
### Read configuration
#[ -r "$SYSCONFIG" ] && source "$SYSCONFIG"
 
FILES=(/etc/sysconfig/hhvm_*);
# check for alternative config schema
if [ -r "${FILES[0]}" ]; then
	CONFIGS=();
  	for FILE in "${FILES[@]}";
  	do
		# remove prefix
		#echo "${FILE} ==> file"
		NAME=${FILE#/etc/sysconfig/};
		# check optional second param
		if [ $# -ne 2 ];
		then
		  # add to config array
		  CONFIGS+=($NAME);
		elif [ "$2" == "$NAME" ];
		then
		  # use only one hhvm
		  CONFIGS=($NAME);
		  break;
		fi;
  	done;
  if [ ${#CONFIGS[@]} == 0 ];
  then
    echo "Config not exist for: $2" >&2;
    exit 1;
  fi;
else
  CONFIGS=(hhvm);
fi;
 
CONFIG_NUM=${#CONFIGS[@]};
for ((i=0; i < $CONFIG_NUM; i++)); do
  NAME=${CONFIGS[${i}]};
  PIDFILE="/var/run/hhvm/${NAME}/hhvm.pid";
  #echo "LOOP \"$CONFIG_NUM\""
  #echo "config ==> ${NAME}"
  #echo "$PIDFILE ==> PID"
 
##
 
RETVAL=0
#prog="hhvm"
prog="${NAME}"
exec="/usr/bin/hhvm"
source "/etc/sysconfig/${NAME}"
desc="HHVM"
 
start() {
	echo -n $"Starting $desc (${NAME}): "
	[ ! -d /var/run/hhvm/${NAME} ] &&
		mkdir -p /var/run/hhvm/${NAME} &&
		chown -R $USER /var/run/hhvm/${NAME}
	daemon $exec --mode daemon --user $USER -v PidFile=$PIDFILE $OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}
 
stop() {
	echo -n $"Shutting down $desc ($prog): "
	killproc -p $PIDFILE hhvm 
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}
 
restart() {
	stop
	start
}
 
reload() {
	echo -n $"Reloading $desc ($prog): "
	killproc $prog -HUP
	RETVAL=$?
	echo
	return $RETVAL
}
 
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
  reload)
	reload
	;;
  status)
	status -p $PIDFILE $prog
	RETVAL=$?
	;;
   *)
	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	RETVAL=1
esac
 
##$RETVAL
 
done;
