RPM_NAME        = re2c
RPM_SUMMARY     = Tool for writing very fast and very flexible scanners
RPM_LICENSE     = GPL
RPM_VERSION     = 0.13.7.5
RPM_RELEASE     = 1
RPM_SOURCEN0    = re2c-$(RPM_VERSION)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = http://sourceforge.net/projects/$(RPM_NAME)/files/$(RPM_NAME)/$(RPM_VERSION)/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
