RPM_NAME        = libmhash
RPM_SUMMARY     = Libmhash is a library that provides a uniform interface to several hash algorithms.
RPM_LICENSE     = LGPLv2
RPM_VERSION     = 0.9.9.9
RPM_RELEASE     = 1
RPM_SOURCEN0    = mhash-$(RPM_VERSION)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = http://sourceforge.net/projects/mhash/files/mhash/$(RPM_VERSION)/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
