RPM_NAME        = varnish
RPM_SUMMARY	= High-performance HTTP accelerator
RPM_LICENSE	= BSD
RPM_VERSION     = 3.0.4
RPM_RELEASE     = 1
RPM_SOURCE0     = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL		= http://repo.varnish-cache.org/source/$(RPM_SOURCE0)

# Makefile internals from here on:

ROOTDIR = $(shell pwd)/../
include $(ROOTDIR)Makefile.includes
include $(ROOTDIR)Makefile.pkg_stdrules
