RPM_NAME        = ImageMagick
RPM_SUMMARY     = An X application for displaying and manipulating images
RPM_LICENSE     = ImageMagick
RPM_VERSION     = 6.8.8
RPM_VERSIO2	= 6.8.8-7
RPM_RELEASE     = 7
RPM_SOURCEN0    = $(RPM_NAME)-$(RPM_VERSIO2)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = http://ftp.nluug.nl/ImageMagick/$(RPM_SOURCE0)

# Makefile internals from here on:

ROOTDIR = $(shell pwd)/../
include $(ROOTDIR)Makefile.includes
include $(ROOTDIR)Makefile.pkg_stdrules
