RPM_NAME        = ImageMagick
RPM_SUMMARY     = An X application for displaying and manipulating images
RPM_LICENSE     = ImageMagick
RPM_VERSION     = 6.8.9
RPM_VERSIO2	= 6.8.9-0
RPM_RELEASE     = 1
RPM_SOURCEN0    = $(RPM_NAME)-$(RPM_VERSIO2)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL         = http://ftp.nluug.nl/ImageMagick/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
