RPM_NAME        = boost
RPM_SUMMARY     = The free peer-reviewed portable C++ source libraries
RPM_LICENSE     = Boost and MIT and Python
RPM_VERSION     = 1.55.0
RPM_VERSIO2	= 1_55_0
RPM_RELEASE     = 1
RPM_SOURCEN0	= $(RPM_NAME)_$(RPM_VERSIO2)
RPM_SOURCE0     = $(RPM_SOURCEN0).tar.gz
RPM_URL		= http://downloads.sourceforge.net/project/boost/boost/$(RPM_VERSION)/$(RPM_SOURCE0)

#RPM_BUILD_DEP	= libicu

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
