RPM_NAME        = boost
RPM_SUMMARY     = The free peer-reviewed portable C++ source libraries
RPM_LICENSE     = Boost and MIT and Python
RPM_VERSION     = 1.55.0
RPM_VERSION2	= 1_55_0
RPM_RELEASE     = 1
RPM_SOURCE0N	= $(RPM_NAME)_$(RPM_VERSION2)
RPM_SOURCE0     = $(RPM_SOURCE0N).tar.gz
RPM_URL		= http://downloads.sourceforge.net/project/boost/boost/$(RPM_VERSION2)/$(RPM_SOURCE0)

# Makefile internals from here on:

ROOTDIR = $(shell pwd)/../
include $(ROOTDIR)Makefile.includes

all: build_default

