RPM_NAME        = tbb
RPM_SUMMARY     = The Threading Building Blocks library abstracts low-level threading details
RPM_LICENSE     = GPLv2 with exceptions
RPM_VERSION     = 4.2
RPM_RELEASE     = 1
RPM_SOURCEN0    = tbb42_20140122oss
RPM_SOURCE0     = $(RPM_SOURCEN0)_src.tgz
RPM_URL         = https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/$(RPM_SOURCE0)

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
