#!/bin/bash

ROOTDIR=`readlink -m \`dirname \\\`basename $0\\\`\``
NAME="${1:-"php53"}"
VERSION=${2:-"4.5"}
RELEASE=${3:-"1"}
IONCUBE_TAR=${4:-"ioncube_loaders_lin_x86-64.tar.gz"}


PHP_MINOR="$(echo $NAME | grep -Po "[0-9]$")"
IONCUBE_SO="ioncube_loader_lin_5.$PHP_MINOR.so"

SPEC=$NAME-extra-ioncube.spec

PHP_SAPI_VERSION=`phpize -v | awk '$1 ~ /PHP/ { print $4; }'`

sed -e "s/PVERSION/$VERSION/g" \
    -e "s/PIONCUBE/$IONCUBE_SO/g" \
    -e "s/PNAME/$NAME/g" \
    -e "s/TARFILE/$IONCUBE_TAR/g" \
    -e "s/SAPIVER/$PHP_SAPI_VERSION/g" \
    -e "s/PRELEASE/$RELEASE/g" \
    > $SPEC <<'EOF'
%global phpname		PNAME
%global ionver		PVERSION
%global peardir		%{_datadir}/pear
%global sapiver		SAPIVER

Summary: PHP IONCube Loader
Name: PNAME-extra-ioncube
Version: %{ionver}
Release: PRELEASE
Group: Networking/Daemons
Source0: TARFILE
License: Proprietary IONCube
BuildRoot: %{_tmppath}/%{name}-%{version}-buildroot
BuildRequires: %{phpname}-devel
Requires: %{phpname}-common
Provides: %{phpname}-extra-ioncube, php-extra-ioncube
%description
PHP Language - IONCube Loader


%prep

%setup -q -n ioncube


%build
cat > ioncube.ini <<EOINI
extension=ioncube.so
EOINI


%install

%{__mkdir_p} ${RPM_BUILD_ROOT}/%{_libdir}/%{sapiver}/
%{__mkdir_p} ${RPM_BUILD_ROOT}/%{_sysconfdir}/php.d/
%{__install} -m0644 PIONCUBE ${RPM_BUILD_ROOT}/%{_libdir}/%{sapiver}/ioncube.so
%{__install} -m0644 ioncube.ini ${RPM_BUILD_ROOT}/%{_sysconfdir}/php.d/ioncube.ini



%clean

%changelog

%check

%files
%defattr(-,root,root)
%config(noreplace) %{_sysconfdir}/php.d/ioncube.ini
%{_libdir}/%{sapiver}/ioncube.so

EOF
