#!/bin/bash

NAME="${1:-"php53"}"
EXTNAME="${2:-"memcache"}"
VERSION="${3:-"3.0.5"}"
RELEASE=${4:-"1"}
EXT_FILE=${5:-"memcache-3.0.5.tgz"}

TAR=$EXTNAME-$VERSION.tgz
SPEC=$NAME-pecl-$EXTNAME-$VERSION.spec

PHP_SAPI_VERSION=`phpize -v | awk '$1 ~ /PHP/ { print $4; }'`

sed -e "s/PVERSION/$VERSION/g" \
    -e "s/PEXTNAME/$EXTNAME/g" \
    -e "s/PNAME/$NAME/g" \
    -e "s/SAPIVER/$PHP_SAPI_VERSION/g" \
    -e "s/PRELEASE/$RELEASE/g" \
    -e "s/PEXTFILE/$EXT_FILE/g" \
    > $SPEC <<'EOF'
%global phpname		PNAME
%global extname		PEXTNAME
%global	extver		PVERSION
%global	extrel		PRELEASE
%global peardir		%{_datadir}/pear
%global sapiver		SAPIVER

Summary: PHP PECL - %{extname} %{extver}
Name: %{phpname}-pecl-%{extname}
Version: %{extver}
Release: %{extrel}
Group: Networking/Daemons
Source0: PEXTFILE
License: PHP License
BuildRoot: %{_tmppath}/%{name}-%{version}-buildroot
BuildRequires: %{phpname}-devel
Requires: %{phpname}-common
Provides: %{phpname}-pecl-%{extname}, php-pecl-%{extname}
%description
PHP Language - PECL %{extname} %{extver}


%prep

%setup -D -q -n %{extname}-%{extver}


%build
module_name="`echo %{extname} | sed -e 's/\(.*\)/\L\1/'`.so"

phpize
%configure
make %{?_smp_mflags} CFLAGS="%{optflags}"

echo "extension=${module_name}" >> extension.ini

%install
module_name="`echo %{extname} | sed -e 's/\(.*\)/\L\1/'`.so"

%{__mkdir_p} ${RPM_BUILD_ROOT}%{_libdir}/%{sapiver}/
%{__mkdir_p} ${RPM_BUILD_ROOT}%{_sysconfdir}/php.d/
%{__install} -m0644  extension.ini	  ${RPM_BUILD_ROOT}%{_sysconfdir}/php.d/PEXTNAME.ini
%{__install} -m0644 modules/$module_name ${RPM_BUILD_ROOT}%{_libdir}/%{sapiver}/$module_name

%clean

%changelog

%check
#make test

%files
%defattr(-,root,root)
%config(noreplace) %{_sysconfdir}/php.d/%{extname}.ini
%{_libdir}/%{sapiver}/*

EOF
