RPM_NAME         = bitfront
RPM_SUMMARY      = bitfront
RPM_LICENSE      = Apache Software License
RPM_VERSION      = 2.0.7
RPM_RELEASE      = 1
RPM_SOURCE0      = $(RPM_NAME)-$(RPM_VERSION).tar.gz
RPM_URL          = gitolite@git.int.prg.relbit.com:bitfront.git
RPM_SOURCE_ISGIT = 1
RPM_GIT_BRANCH   = 1019_rails4
RPM_SOURCES      = etc-init.d-bitfront etc-logrotate.d-bitfront usr-sbin-bitfront usr-sbin-bitfront-console

# Makefile internals from here on:

MAKEDIR = $(shell pwd)/../.make/
include $(MAKEDIR)Makefile.includes
include $(MAKEDIR)Makefile.pkg_stdrules
